#!/usr/bin/perl
use lib "lib";
use MIME::Lite;

$msg = new MIME::Lite 
     To       => 'eryq@enteract.com',
     Subject  => 'GIF test',
     Type     => 'image/gif',		       
     Encoding => 'base64',
     Path     => "cat ./docs/MIME/mime-sm.gif |";
print $msg->stringify;

#$msg = new MIME::Lite 
#     To       => 'eryq@enteract.com',
#     Subject  => 'GIF test',
#     Type     => 'image/gif',		       
#     Encoding => 'base64',
#     Path     => "./docs/MIME/mime-sm.gif";
#
#$msg = new MIME::Lite 
#     To       => 'eryq@enteract.com',
#     Subject  => 'GIF test',
#     Type     => 'image/gif',		       
#     Encoding => 'base64',
#     Path     => "./docs/MIME/mime-sm.gif",
#     Filename => "my-mime.gif";




