--- #YAML:1.0
name:               MIME-Lite
version:            3.023
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::Date::Format:  1.000
    File::Basename:       ~
    File::Spec:           0
    Mail::Address:        1.62
    MIME::Base64:         ~
    MIME::QuotedPrint:    ~
    MIME::Types:          1.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
