---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MIME-Lite
no_index:
  directory:
    - t
    - inc
requires:
  Email::Date::Format: 1.000
  File::Basename: 0
  File::Spec: 0
  Mail::Address: 1.62
resources:
  x_Repository: http://github.com/rjbs/mime-lite
version: 3.029
