#!/usr/bin/perl
use lib "lib";
use MIME::Lite;

$msg = new MIME::Lite 
     To       => 'me@somewhere.com',
     Subject  => 'GIF test',
     Type     => 'image/gif',		       
     Encoding => 'base64',
     Path     => "cat ./docs/MIME/mime-sm.gif |";
print $msg->stringify;



